
spring:
  application:
    name: cloud-payment-order
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
server:
  port: 80