server:
  port: 8082

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.50.20
      port: 8500

      discovery:
        service-name: ${spring.application.name}
logging:
  level:
    root: debug
