server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  cloud:
    zookeeper:
      #注册到zookeeper  zookeeper IP PORT
      connect-string: 192.168.50.20:2181
logging:
  level:
    root: debug
